name: famitree
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  connectivity: ^3.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  flashy_tab_bar2: ^0.0.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slider_drawer: ^2.1.3
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.0
  google_sign_in: ^6.2.1
  graphview: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
