// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwjpKSZqog4VTSWp_OSxuz5TLyJVVzTo',
    appId: '1:801072513955:web:d346dc631f936ba7f09016',
    messagingSenderId: '801072513955',
    projectId: 'myfam-d7a10',
    authDomain: 'myfam-d7a10.firebaseapp.com',
    storageBucket: 'myfam-d7a10.appspot.com',
    measurementId: 'G-HQCFSKZ0V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdFCg-Ob6xKcdEeqqHUzu0V0I_xqmMhL8',
    appId: '1:801072513955:android:6cfb214d0ed3e347f09016',
    messagingSenderId: '801072513955',
    projectId: 'myfam-d7a10',
    storageBucket: 'myfam-d7a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Nun9XCJn-jW-oAGJaATYm2AzHPUSIso',
    appId: '1:801072513955:ios:21718fe9e958419af09016',
    messagingSenderId: '801072513955',
    projectId: 'myfam-d7a10',
    storageBucket: 'myfam-d7a10.appspot.com',
    iosBundleId: 'com.example.famitree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Nun9XCJn-jW-oAGJaATYm2AzHPUSIso',
    appId: '1:801072513955:ios:21718fe9e958419af09016',
    messagingSenderId: '801072513955',
    projectId: 'myfam-d7a10',
    storageBucket: 'myfam-d7a10.appspot.com',
    iosBundleId: 'com.example.famitree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQwjpKSZqog4VTSWp_OSxuz5TLyJVVzTo',
    appId: '1:801072513955:web:758301b05ace14f8f09016',
    messagingSenderId: '801072513955',
    projectId: 'myfam-d7a10',
    authDomain: 'myfam-d7a10.firebaseapp.com',
    storageBucket: 'myfam-d7a10.appspot.com',
    measurementId: 'G-P7H67BRZXJ',
  );
}
